"""empty message

Revision ID: 2c31a4c4fbe5
Revises: 85016e8d12ea
Create Date: 2020-02-10 19:09:42.985817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c31a4c4fbe5'
down_revision = '85016e8d12ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(), nullable=True))
    op.drop_column('show', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('datetime', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
